/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LandlordsRouteImport } from './routes/landlords'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as IndexRouteImport } from './routes/index'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordsRoute = LandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/landlords': typeof LandlordsRoute
  '/notifications': typeof NotificationsRoute
  '/properties': typeof PropertiesRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/landlords': typeof LandlordsRoute
  '/notifications': typeof NotificationsRoute
  '/properties': typeof PropertiesRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/landlords': typeof LandlordsRoute
  '/notifications': typeof NotificationsRoute
  '/properties': typeof PropertiesRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/analytics'
    | '/buildings'
    | '/landlords'
    | '/notifications'
    | '/properties'
    | '/revenue'
    | '/settings'
    | '/subscriptions'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/analytics'
    | '/buildings'
    | '/landlords'
    | '/notifications'
    | '/properties'
    | '/revenue'
    | '/settings'
    | '/subscriptions'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/analytics'
    | '/buildings'
    | '/landlords'
    | '/notifications'
    | '/properties'
    | '/revenue'
    | '/settings'
    | '/subscriptions'
    | '/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuildingsRoute: typeof BuildingsRoute
  LandlordsRoute: typeof LandlordsRoute
  NotificationsRoute: typeof NotificationsRoute
  PropertiesRoute: typeof PropertiesRoute
  RevenueRoute: typeof RevenueRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlords': {
      id: '/landlords'
      path: '/landlords'
      fullPath: '/landlords'
      preLoaderRoute: typeof LandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuildingsRoute: BuildingsRoute,
  LandlordsRoute: LandlordsRoute,
  NotificationsRoute: NotificationsRoute,
  PropertiesRoute: PropertiesRoute,
  RevenueRoute: RevenueRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
